FROM ubuntu:disco-20190204

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    asciidoc \
    ccache \
    clang-7 \
    cmake \
    docbook-xml \
    docbook-xsl \
    git \
    iwyu \
    libglib2.0-dev \
    libx11-dev \
    libxext-dev \
    libxinerama-dev \
    libxml2-utils \
    ninja-build \
    pkg-config \
    xsltproc
